# Starter pipeline
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'aks_dev-default'
    strategy: 'canary'
    percentage: '0'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
        - main

        pool:
          vmImage: 'ubuntu-1604' # set to windows-latest or another Windows vmImage for Windows builds

        variables:
          imageName: 'pipelines-javascript-docker'

        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile